### ISSUE TITLE
add discordbotlist.co

### ISSUE THREAD

**Issue by eepyfemboi** [Developer-Dungeon-Studio/Discord-Bot-Lists#16]
add discordbotlist.co (its a new botlist, i just got it working like a week ago)

**Comment by mezotv** [comment]
Ill give it a look on the weekend feel free to make a pr yourself in the meantime!

**Comment by mezotv** [comment]
Looks just like any other botlist soI dont think there id a benefit in adding it. Thanks for making an issue tho!
